"""Small, dependency-light helpers for exploring the NSD-Imagery release."""

from .analysis import (
    average_by_target,
    balanced_split_reliability,
    balanced_split_identification,
    correlation_rdm,
    cosine_rdm,
    crossvalidated_dot_rdm,
    exact_class_label_permutation_test,
    exact_label_permutation_test,
    exact_sign_flip_test,
    independent_group_reliability,
    leave_one_target_out_rdm_spearman,
    nearest_centroid_predict,
    rdm_noise_ceiling,
    rdm_spearman,
    target_rdm,
    upper_triangle,
    zscore_within_groups,
)

from .io import (
    RUN_SPECS,
    build_event_table,
    build_run_table,
    describe_hdf5,
    extract_masked_betas,
    find_data_root,
    infer_beta_layout,
    load_behavior,
    load_roi,
    load_target_table,
    paths_for_subject,
    read_ctab,
    summarize_glmsingle_design,
    validate_download,
)

__all__ = [
    "RUN_SPECS",
    "average_by_target",
    "balanced_split_identification",
    "balanced_split_reliability",
    "build_event_table",
    "build_run_table",
    "correlation_rdm",
    "cosine_rdm",
    "crossvalidated_dot_rdm",
    "describe_hdf5",
    "extract_masked_betas",
    "exact_class_label_permutation_test",
    "exact_label_permutation_test",
    "exact_sign_flip_test",
    "find_data_root",
    "infer_beta_layout",
    "independent_group_reliability",
    "leave_one_target_out_rdm_spearman",
    "load_behavior",
    "load_roi",
    "load_target_table",
    "nearest_centroid_predict",
    "paths_for_subject",
    "read_ctab",
    "rdm_spearman",
    "rdm_noise_ceiling",
    "summarize_glmsingle_design",
    "target_rdm",
    "upper_triangle",
    "validate_download",
    "zscore_within_groups",
]
